/* ==========================================================================
   차시 경량 메타데이터 (목록·라우팅·일정·이전/다음·공개범위용).
   본문(theoryBlocks·quiz 등)은 여기 없고, SessionPage 가 loadSession(id) 로
   차시별 청크를 동적 import 한다. → 잠긴 차시 본문이 메인 번들에 안 실린다.

   ⚠️ session01~15.ts 의 메타데이터가 바뀌면 이 파일도 함께 고쳐야 한다.
   dev 모드에서 실제 본문을 로드해 불일치를 콘솔 경고로 검사한다(index.ts).
   ========================================================================== */

import type { SessionMeta } from "@/types/content";

export const sessionMetas: SessionMeta[] = [
  { id: "01", slug: "digital-education-foundations", title: "디지털 교육의 출발점: 교육이 먼저, 기술은 수단", category: "theory", summary: "교육과 기술의 관계, 디지털 교육의 정의, ISTE와 UDL을 이해한다.", duration: 90, level: "입문", keywords: ["디지털 교육", "에듀테크", "Alignment", "ISTE", "UDL"], theoryRatio: 100, practiceRatio: 0, published: true, lastUpdated: "2026-07-10" },
  { id: "02", slug: "curriculum-future-classroom", title: "2022 개정 교육과정과 미래 교실", category: "theory", summary: "학습자 주도성, 기초소양의 확장, 하이테크·하이터치의 균형을 이해한다.", duration: 90, level: "입문", keywords: ["2022 개정 교육과정", "학습자 주도성", "기초소양", "하이터치", "과정 중심 평가"], theoryRatio: 100, practiceRatio: 0, published: true, lastUpdated: "2026-07-10" },
  { id: "03", slug: "personalized-learning-tpack-terms", title: "개인 맞춤형 학습, ITS, TPACK과 에듀테크 핵심 용어", category: "theory", summary: "개인 맞춤형 학습의 시스템적 이해, TPACK, 그리고 에듀테크 핵심 용어를 구조화한다.", duration: 90, level: "입문", keywords: ["개인 맞춤형 학습", "ITS", "TPACK", "LMS", "에듀테크 용어"], theoryRatio: 100, practiceRatio: 0, published: true, lastUpdated: "2026-07-10" },
  { id: "04", slug: "google-workspace-ecosystem", title: "Google Workspace for Education 생태계", category: "google", summary: "하나의 계정과 Drive를 중심으로 연결되는 Google 학교 협업 생태계를 이해한다.", duration: 90, level: "입문", keywords: ["Google Workspace", "Drive", "Classroom", "Forms", "교육용 계정"], theoryRatio: 60, practiceRatio: 40, published: true, lastUpdated: "2026-07-10" },
  { id: "05", slug: "google-classroom-brisk", title: "Google Classroom과 Brisk Teaching 실습", category: "google", summary: "수업의 배포–수행–제출–피드백 흐름을 설계하고, AI 생성 자료를 검토하는 원칙을 익힌다.", duration: 90, level: "중급", keywords: ["Google Classroom", "Brisk Teaching", "루브릭", "AI 자료 검토", "형성평가"], theoryRatio: 50, practiceRatio: 50, published: true, lastUpdated: "2026-07-10" },
  { id: "06", slug: "microsoft-365-education-a3", title: "Microsoft 365 Education과 A3 생태계", category: "microsoft", summary: "MS365 Education을 수업·평가·협업·기기관리·학생지원이 연결된 학교 플랫폼으로 이해한다.", duration: 90, level: "입문", keywords: ["Microsoft 365 Education", "A1 A3 A5", "Teams", "Intune", "Learning Accelerators"], theoryRatio: 60, practiceRatio: 40, published: true, lastUpdated: "2026-07-10" },
  { id: "07", slug: "onedrive-sharepoint-collaboration", title: "OneDrive와 SharePoint 기반 파일 협업", category: "microsoft", summary: "개인 저장소(OneDrive)와 공동 저장소(SharePoint)의 차이를 이해하고 협업 구조를 설계한다.", duration: 90, level: "중급", keywords: ["OneDrive", "SharePoint", "링크 공유", "버전 기록", "파일 요청"], theoryRatio: 55, practiceRatio: 45, published: true, lastUpdated: "2026-07-10" },
  { id: "08", slug: "teams-for-education-accelerators", title: "Teams for Education과 학습 가속기", category: "microsoft", summary: "Teams를 수업 자료·과제·평가·데이터가 연결되는 교육 허브로 설계하고, 학습 데이터를 해석한다.", duration: 90, level: "중급", keywords: ["Teams", "채널", "과제", "Learning Accelerators", "학습 데이터"], theoryRatio: 50, practiceRatio: 50, published: true, lastUpdated: "2026-07-10" },
  { id: "09", slug: "onenote-class-notebook-whiteboard", title: "OneNote Class Notebook과 Whiteboard", category: "microsoft", summary: "자료 제공·학생 개별 작업·협업을 한 구조로 운영하는 Class Notebook과 Whiteboard를 익힌다.", duration: 90, level: "중급", keywords: ["OneNote", "Class Notebook", "협업 공간", "Whiteboard", "포트폴리오"], theoryRatio: 55, practiceRatio: 45, published: true, lastUpdated: "2026-07-10" },
  { id: "10", slug: "microsoft-365-other-tools-workflow", title: "Microsoft 365 기타 도구와 교사 워크플로", category: "microsoft", summary: "Forms·Outlook·To Do·Copilot·Loop·Sway·Clipchamp 등을 조합해 업무·수업 흐름을 줄인다.", duration: 90, level: "중급", keywords: ["Forms", "Copilot", "Loop", "Sway", "Clipchamp", "도구 선택 매트릭스"], theoryRatio: 45, practiceRatio: 55, published: true, lastUpdated: "2026-07-10" },
  { id: "11", slug: "quiz-game-based-learning", title: "퀴즈·게임 기반 학습과 콘텐츠 저작 도구", category: "edutech", summary: "게임성이 학습 목표를 강화하도록 설계하고, 대표 퀴즈 도구를 기준으로 비교한다.", duration: 90, level: "중급", keywords: ["Kahoot", "Blooket", "Quizlet", "게임 기반 학습", "형성평가"], theoryRatio: 45, practiceRatio: 55, published: true, lastUpdated: "2026-07-10" },
  { id: "12", slug: "metaverse-xr-process-assessment", title: "메타버스·XR와 과정 중심 평가", category: "edutech", summary: "몰입 경험이 학습 목표와 연결되도록 설계하고, 과정 중심 평가 도구로 사고·수행의 증거를 모은다.", duration: 90, level: "심화", keywords: ["메타버스", "XR", "몰입감", "과정 중심 평가", "루브릭"], theoryRatio: 45, practiceRatio: 55, published: true, lastUpdated: "2026-07-10" },
  { id: "13", slug: "generative-ai-ml-to-agent", title: "생성형 AI의 이해: 머신러닝에서 LLM과 Agent까지", category: "genai", summary: "생성형 AI의 발전 과정과 원리, 그리고 한계를 함께 이해한다.", duration: 90, level: "심화", keywords: ["머신러닝", "Transformer", "LLM", "Agent", "할루시네이션"], theoryRatio: 55, practiceRatio: 45, published: true, lastUpdated: "2026-07-10" },
  { id: "14", slug: "generative-ai-in-practice-multimodal", title: "생성형 AI의 교육적 실제와 멀티모달 활용", category: "genai", summary: "생성형 AI를 수업 설계·자료·피드백을 돕는 협력 도구로 활용하고, 프롬프트를 설계한다.", duration: 90, level: "심화", keywords: ["프롬프트 설계", "NotebookLM", "AI Studio", "멀티모달", "사실 검증"], theoryRatio: 40, practiceRatio: 60, published: true, lastUpdated: "2026-07-10" },
  { id: "15", slug: "vibe-coding-capstone", title: "바이브 코딩과 교육용 웹앱 제작 캡스톤", category: "genai", summary: "교육 문제 정의부터 프로토타입·검증·배포까지, 바이브 코딩으로 교육용 웹앱을 만든다.", duration: 120, level: "심화", keywords: ["바이브 코딩", "노코드", "프로토타입", "배포", "캡스톤"], theoryRatio: 35, practiceRatio: 65, published: true, lastUpdated: "2026-07-10" },
];
